### ISSUE TITLE
Audio: TI SN76489AN vs Sega PSG

### ISSUE THREAD

**Issue by carmiker** [drhelius/Gearcoleco#1]
The TI chip does not double the noise channel's volume, so removing * 2 here will make it more accurate:
https://github.com/drhelius/Gearcoleco/blob/003b5c9b562db6736363f47c7cb5ffef30bf4561/src/audio/Sms_Apu.cpp#L109

Tapped bits for ColecoVision (and SG-1000) are 0x0003, not 0x0009:
https://github.com/drhelius/Gearcoleco/blob/003b5c9b562db6736363f47c7cb5ffef30bf4561/src/audio/Sms_Apu.cpp#L211

LFSR is one bit shorter on the TI chip (same on SG-1000) vs the Sega PSG, this should be 15 rather than 16:
https://github.com/drhelius/Gearcoleco/blob/003b5c9b562db6736363f47c7cb5ffef30bf4561/src/audio/Sms_Apu.cpp#L212

There is also the issue of PCM samples having too high a pitch. In Sewer Sam and Squish'em Sam, you can see this exhibited. I have not truly figured out the answer to this entire question, but it does have to do with not flipping the waveform when the length counter reload value is 1, or in the case of Squish'em Sam, 16 seems to be the magic number. There is also the write delay to keep in mind when writing data to the PSG. Here are some references from JollyCV that explain a bit of this:
https://gitlab.com/jgemu/jollycv/-/blob/master/core/jcv_psg.c#L152
https://gitlab.com/jgemu/jollycv/-/blob/master/core/jcv_memio.c#L100

I think the SMS APU code you're using currently is doing PCM samples correctly, since I do hear the samples, but the pitch is wrong. I think you can get away with simply introducing a delay on writes to fix the pitch.

Hope this helps!

**Comment by drhelius** [comment]
Thanks for the effort, it definitely helps.
I was on vacation, I'll have a look asap.
