### ISSUE TITLE
Cabbage Patch Kids game option screen issue - Libretro core

### ISSUE THREAD

**Issue by unit3uk** [drhelius/Gearcoleco#18]
After the game is over in Cabbage Patch Kids, the game automatically restarts instead of going to the "Game Option" screen. This also happens in Chuck Norris - Superkicks.

**Comment by drhelius** [comment]
Thanks for reporting

**Comment by msheehan79** [comment]
I believe this issue should be fixed now with the input update to the libretro core on #28 , as it was caused by the same problem as #27 .
