### ISSUE TITLE
error on "make"

### ISSUE THREAD

**Issue by masrourmouad** [drhelius/Gearcoleco#2]
g++ 4.9
 
git clone https://github.com/drhelius/Gearcoleco.git
Clonage dans 'Gearcoleco'...
remote: Enumerating objects: 616, done.
remote: Counting objects: 100% (616/616), done.
remote: Compressing objects: 100% (458/458), done.
remote: Total 616 (delta 295), reused 456 (delta 143), pack-reused 0
Réception d'objets: 100% (616/616), 5.00 MiB | 1.58 MiB/s, fait.
Résolution des deltas: 100% (295/295), fait.
Vérification de la connectivité... fait.
momo@momo:~/dev$ cd Gearcoleco/
momo@momo:~/dev/Gearcoleco$ cd platforms/linux/
momo@momo:~/dev/Gearcoleco/platforms/linux$ make
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o main.o ../desktop-shared/main.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o emu.o ../desktop-shared/emu.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o gui.o ../desktop-shared/gui.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o gui_debug.o ../desktop-shared/gui_debug.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o application.o ../desktop-shared/application.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o config.o ../desktop-shared/config.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o renderer.o ../desktop-shared/renderer.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui_impl_sdl.o ../desktop-shared/imgui/imgui_impl_sdl.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui_impl_opengl2.o ../desktop-shared/imgui/imgui_impl_opengl2.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui.o ../desktop-shared/imgui/imgui.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui_demo.o ../desktop-shared/imgui/imgui_demo.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui_draw.o ../desktop-shared/imgui/imgui_draw.cpp
../desktop-shared/imgui/imgui_draw.cpp: In function ‘bool ImFontAtlasBuildWithStbTruetype(ImFontAtlas*)’:
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::user_allocator_context’ [-Wmissing-field-initializers]
     stbtt_pack_context spc = {};
                               ^
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::pack_info’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::width’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::height’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::stride_in_bytes’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::padding’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::skip_missing’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::h_oversample’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::v_oversample’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::pixels’ [-Wmissing-field-initializers]
../desktop-shared/imgui/imgui_draw.cpp:2103:31: warning: missing initializer for member ‘stbtt_pack_context::nodes’ [-Wmissing-field-initializers]
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o imgui_widgets.o ../desktop-shared/imgui/imgui_widgets.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o ImGuiFileBrowser.o ../desktop-shared/FileBrowser/ImGuiFileBrowser.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o Audio.o ../../src/Audio.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o Cartridge.o ../../src/Cartridge.cpp
In file included from ../../src/miniz/miniz.c:1:0,
                 from ../../src/Cartridge.cpp:24:
../../src/miniz/miniz.c: In function ‘mz_bool mz_zip_validate_file(mz_zip_archive*, mz_uint, mz_uint)’:
../../src/miniz/miniz.h:547:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 #define MZ_READ_LE32(p) *((const mz_uint32 *)(p))
                                                 ^
../../src/miniz/miniz.c:5353:19: note: in expansion of macro ‘MZ_READ_LE32’
         has_id = (MZ_READ_LE32(descriptor_buf) == MZ_ZIP_DATA_DESCRIPTOR_ID);
                   ^
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o GearcolecoCore.o ../../src/GearcolecoCore.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o Input.o ../../src/Input.cpp
g++ -I../ -I../../ -Wall -Wextra -Wformat -std=c++11 -DEMULATOR_BUILD=\""d341487"\" -DNDEBUG -O3 -flto `sdl2-config --cflags` -c -o Memory.o ../../src/Memory.cpp
../../src/Memory.cpp:371:10: error: #elif with no expression
     #elif
          ^
../desktop-shared/Makefile.common:93: recipe for target 'Memory.o' failed
make: *** [Memory.o] Error 1

**Comment by drhelius** [comment]
Fixed, it was a typo, thanks!
