### ISSUE TITLE
Unsupported games

### ISSUE THREAD

**Issue by AngelofMe** [drhelius/Gearcoleco#20]
-  Destructor (1984) (Coleco)
    -  50% (2.8.1) Controls: Driving Controller emulation required
    -  Size: 32768, MD5: ec72a0e3bebe07ba631a8dcb750c1591,
    -  SH1: 35283c51f448d877625049266c0c4687bf57ab42
-  Donkey Kong Arcade (Oct 25) (2005) (Eduardo Mello)
    -  50% (2.8.1) Other: Requires Opcode Memory Extension emulation
    -  Size: 32768, MD5: e602e72072766ec2159cf13469e7ef15,
    -  SH1: 6a754455ec9f6f9811f2fb947c5ac750474dc8e8
-  Dukes of Hazzard, The (1984) (Warner Bros) [!]
    -  50% (2.8.1) Controls: Steering wheel emulation required
    -  Size: 32768, MD5: dbd4f21702be17775e84b2fb6c534c94,
    -  SH1: 162c7ad3266e02aa88983fa4ece7a77bc1cb9c7a
-  Pac-Man Collection Demo by Opcode (2006) (PD)
    -  10% (2.8.1) Stuck: Stuck on home screen
    -  Size: 32768, MD5: 0021c6f3f52cc6a55a3c14bab8a6339e,
    -  SH1: d6b67e8f43afe666cdd79a718ddf808e27d6512d
-  Slither (1983) (Century II)
    -  50% (2.8.1) Controls: Requires Roller Controller emulation
    -  Size: 16384, MD5: 7cdc148dff40389fa1ad012d4734ceed,
    -  SH1: b11de2476f867c7c4efb2977777e12fcb454f10b
-  Super Action Controller Test Cartridge (1983) (Nuvatec)
    -  50% (2.8.1) Controls: Requires Super Action Controller emulation
    -  Size: 16384, MD5: 1210396cb9af270285d25c66fa9c6f6a,
    -  SH1: 0c6840b7bc24a36529f0a80ccef85ee9f409a972
-  Turbo (1982) (Sega)
    -  50% (2.8.1) Controls: Steering wheel emulation required
    -  Size: 16384, MD5: f042ba432716b58d2f5858abcce81b9f,
    -  SH1: 732d1f3b2f24895a1f79d15d830aa989ea12fe5e
-  Yolk's on You, The (1983) (20th Century Fox) (Prototype)
    -  50% (2.8.1) Controls: Steering wheel emulation required
    -  Size: 16384, MD5: c10aaca46d063771339d3e5a0582baad,
    -  SH1: 9b5bfb69d37042d131a5c9576f927e09f44f9666

**Comment by drhelius** [comment]
Thanks for all the info.
They are not supported yet.

**Comment by carmiker** [comment]
I'll just add some more information here.

First, Yolk's on You does not require the driving controller. What it does require is random values in RAM at bootup. Reference: https://gitlab.com/jgemu/jollycv/-/blob/master/src/jcv_memio.c#L285

Second, another game:
Lord of the Dungeon (USA) (Beta)

I've not managed to get Lord of the Dungeon working in JollyCV, and I don't think anyone else has gotten it working either. I suspect it may be a bad dump, or it may just be broken but maybe @drhelius will have better luck than everyone else.

**Comment by drhelius** [comment]
Working now:

- Yolk's on You, The (1983) (20th Century Fox) (Prototype) :white_check_mark:
- Pac-Man Collection Demo by Opcode (2006) (PD) :white_check_mark:

**Comment by drhelius** [comment]
Working now:

- Lord of the Dungeon (requires SRAM) ✅

**Comment by carmiker** [comment]
So the answer was indeed SRAM for Lord of the Dungeon. Great to know this for certain.

**Comment by drhelius** [comment]
Working now:

- Destructor (1984) ✅ 
- Dukes of Hazzard, The (1984) ✅
- Slither (1983) ✅
- Super Action Controller Test Cartridge (1983) ✅
- Turbo (1982) ✅
- Yolk's on You, The (1983) ✅

**Comment by drhelius** [comment]
Closing this as the only one left is Donkey Kong Arcade which requires SGM and SGM is tracked here: #11
