### ISSUE TITLE
Disassembler off?  Not catching code?

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#22]
In an instance it outputs as
RET
LD ($7148), HL
CALL $1FB2
Above this line is correct from the amount I checked, below is what occurred after.
CALL $1FA6
CALL $1FA6
CALL $1F8B
CALL $1F8B
CALL $1F8B
CALL $1F8B
CALL $1F8B
-------------------------this is where it corrected itself
CALL $1FA6

The actual code is after CALL $1FB2 is:
FD,85,48,71.........

Which translates to
FD85  ADD A, IYL
48      LD C, B
71      LD (HL), C
.............
I know this is not a whole lot to go on but is it my setting?
Am I missing something?
Could it be the undocumented Opcode IYL?

**Comment by KPreston2900050** [comment]
Thank you for the feedback and despite me being late to respond, it's just been one of those months.

I am thinking a lot of these errors are on me and not the program.


I would like to add though that there is another users who has been floating around Atari Age because he has a hardware project that is nothing but a custom Raspberry Pi or some deal trying to make it out as the next big ADAM computer.

In any case, if he has not contacted you he has been trying to use open source emulators that everyone else made to run his equipment.  In essence he is trying to use other peoples work to make money without paying them.
Now he has openly admitted on FaceBook to taking your source code and trying to modify it to run ADAM software.

He has been rejected by every Colecovision emulator programmer because he refuses to pay their license fee.
The guy knows how to put hardware together but not smart enough to write his own emulator and now he is trying to use yours.

His statement after being accused of theft, and I may paraphrase, My thinking of open source is that it is open then I should be able to use it any way I want.

The guy's name is Danny Heuvel and he is making something called the ADAM+

Just FYI.

**Comment by drhelius** [comment]
Closing this as it doesn’t look like a bug. Don’t hesitate to open it again if youhave more info.
