### ISSUE TITLE
Super Action Controller buttons

### ISSUE THREAD

**Issue by midd33** [drhelius/Gearcoleco#24]
I couldn't find the option to assign the two extra buttons from a Super Action Controller in your core.  It only shows the left and right buttons from a standard controller.  Games like SA Baseball, Football, Rocky, Frontline, and Star Trek use all 4 buttons during game play.

**Comment by drhelius** [comment]
Thanks for reporting, it's not supported yet

**Comment by drhelius** [comment]
Done.
