### ISSUE TITLE
Feature Request: No Sprite Limit Option

### ISSUE THREAD

**Issue by msheehan79** [drhelius/Gearcoleco#29]
Would be a nice optional feature to provide a means to bypass the 4 sprite per line limit to reduce or remove sprite flicker.  

I know this is not accurate behavior but it is one quality of life feature that is offered on many other emulators that I would love to see included here (including blueMSX, the libretro core I was using for CV prior to trying out gearcoleco).

@drhelius not sure if you are open to introducing this since I didn't see many emulation-altering options in the current core.  If it is a feature you would be OK implementing I do have a change in my fork that adds this for the libretro core only as a core option, I could submit it for your review.

**Comment by drhelius** [comment]
It's a nice featureI see no problem in implementing it but it should be a boolean in Video.h with get/set methods so I can add it to other platforms too

**Comment by msheehan79** [comment]
Thanks! I will review and submit a PR for your review soon.

**Comment by drhelius** [comment]
Fixed in #30
