### ISSUE TITLE
Persistent NO BIOS

### ISSUE THREAD

**Issue by malibu1966** [drhelius/Gearcoleco#33]
Hi there.  I am very confused about how to get this working in RetroARCH.  I have placed the correct BIOS from a recent bios pack with  MD5 2c66f5911e5b42b8ebe113403548eee7 in the system folder.  Even when I try Bruce's Controller Tester that is a downloadable ROM I cannot get it to work.  It just has a black screen that says NO BIOS.

This is on MacOS Monterey 12.6.5 / intel mac.  It's as high as I can go.

**Comment by drhelius** [comment]
https://docs.libretro.com/library/gearcoleco/#bios

Name of the file should be 'colecovision.rom' lowercase.

You can check the correct directory to place it in 'settings>directories>system/BIOS'.

Let me know if you get it working

**Comment by drhelius** [comment]
Closing as stale, please reopen if you can't get it working
