### ISSUE TITLE
Space Panic graphics corruption

### ISSUE THREAD

**Issue by DasGroobinCat** [drhelius/Gearcoleco#34]
In Space Panic the graphics can become corrupted after the 1st level.   The top right corner of the blue border, yellow oxygen level, entire bottom blue border, and number of men disappear.  Looking at the VDP viewer shows the patterns used for these elements turn all black when loading the next level.

Happens almost every time, though I've had this bug trigger on the 2nd or 3rd level on rare occasions.  
Gearcoleco 1.0.1 on Android Retroarch and Gearcoleco 1.0.0 on Windows 10.

![SpacePanic](https://github.com/drhelius/Gearcoleco/assets/132780914/d325aa86-ee08-42b1-ac1e-44af51e0a2ee)

**Comment by drhelius** [comment]
Thanks for this thorough report!

**Comment by drhelius** [comment]
Fixed!
A timing issue with the VBLANK interrupt trigger it in the middle of $1FC4 BIOS call and resulted in bad address being used to load sprite data.
