### ISSUE TITLE
Colecovision Memory Mapping

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#35]
done

**Comment by drhelius** [comment]
Could you elaborate on what games are not working well? (apart from Space Panic). Descriptions of actual errors like in #34 are very useful.

CV has 8KB address space for RAM (0x6000-0x7FFF) but just a 1KB RAM chip is connected to it, so it mirrors 0x400 bytes 8 times. ADAM is a different thing but I'm not emulating ADAM.

I think you are a bit confused about how RAM is being handled in the emu. It is not favoring 0x6000 over 0x7000. The address is being checked to be in that area (0x6000-0x7FFF) then is wrapped around to 1KB (0x400), so for example writing or reading to 0x7150 is effectively the same as writing or reading to 0x6150 and you write or get the same byte:

```   
switch (address & 0xE000)
{
        ·
        ·
        case 0x6000:
        {
            return m_pRam[address & 0x03FF];
        }
        ·
        ·
}
```

The actual code is [here](https://github.com/drhelius/Gearcoleco/blob/6c67da0462061a9056cacdb633c6ab4fd8a650f7/src/Memory_inline.h#L25).

TMS9928 is the same to TMS9918, the only different thing is the video output format.
TMS9929 again does not differ to TMS9918 but runs at 50Hz and this is being emulated.
