### ISSUE TITLE
No bios error

### ISSUE THREAD

**Issue by new-penguin** [drhelius/Gearcoleco#49]
OS: EndeavorOS with latest Retroarch and updated core

I've searched for a couple hours but I can't seem to get the Gearcoleco core working; I keep getting the "no bios" screen. I have "colecovision.rom" with md5 checksum 2c66f5911e5b42b8ebe113403548eee7 in my retroarch --> system directory.  I've tried placing the rom in system --> bios directory as well but no luck. The Retroarch desktop menu detects my bios and says it's correct so I don't know what else I can do.

**Comment by drhelius** [comment]
Could you rebuild the core from sources?
If so, you may activate debug traces. This will print a lot of info in stdout and you can see what is going on when loading the BIOS:
```make clean && DEBUG=1 make```

**Comment by drhelius** [comment]
Also, could you share the full path to your BIOS file?

**Comment by new-penguin** [comment]
Full path is /home/tux/.config/retroarch/system/colecovision.rom. 

I built it from source using the AUR and it worked, no problem with the bios or loading a game. Downloading the standalone compiled version here results in "error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory". I didn't install the gearcoleco core from source though and I'm not sure how. Is it an official core that you endorse? I'd love to have it work with Retroarch.

**Comment by new-penguin** [comment]
Ok, I managed to build the libretro core successfully using your instructions "make clean && DEBUG=1 make". I don't know how to debug and give you relevant info but I can probably figure it out.

**Comment by drhelius** [comment]
Great to know you figured it out!

Do you know why was it expecting the bios to be placed in the games directory instead? Is this something you changed in RA?

**Comment by new-penguin** [comment]
As far as I know, the only relevant setting in RA is the system/BIOS directory that you can change and it's set to the default where RA is installed, the usual retroarch/system directory.

My retroarch.cfg has:

system_directory = "~/.config/retroarch/system"
systemfiles_in_content_dir = "true"

I can't find anything in the config even mentioning my colecovision games directory so I'm not sure why something in the code or config is pointing to it.

**Comment by drhelius** [comment]
Thanks for the clarification.
On my side I'm getting whatever RA has configured for the system directory so in your case it should get the correct directory.
```systemfiles_in_content_dir=true``` is probably why it is trying the games directory instead.
Thanks for the help.

**Comment by new-penguin** [comment]
>  systemfiles_in_content_dir=true is probably why it is trying the games directory instead.

You're right. I wasn't thinking about that part. I don't think I changed that setting but at this point, I don't know. I've been awake way too long setting up and configuring RA so I might be wrong. Sorry to waste your time while I overlooked something that should've been obvious.

**Comment by drhelius** [comment]
No problem!
