### ISSUE TITLE
Copy / paste to and from memory

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#50]
Maybe it's just a preference or something that I would find useful if you had the time.

To implement the ability to highlight, copy and paste directly to and from all the memory locations.

It would save a huge amount of time in patching or ripping screen data from VRAM

To and from the clipboard like most other windows applications.

**Comment by KPreston2900050** [comment]
I received an alert that this was closed.
Does that mean the feature was put in because I compiled the latest build and could not seem to get it to work.

TIA

**Comment by drhelius** [comment]
Yes, I rewrote the mem editor entirely. Now you can select and copy/paste (ctrl+c / ctrl+v) mem values. Selection also determines the characters pasted.
You can test it with the binaries generated for each push in the repo if you don't want to build it:
https://github.com/drhelius/Gearcoleco/actions/runs/9449166781
