### ISSUE TITLE
[Issue]: it's always Top+Bottom screen

### ISSUE THREAD

**Issue by SopTheSop25** [drhelius/Gearcoleco#51]
When I set overscan option To OFF, 284 width or 320 width, it's always as Top+Bottom screen

https://github.com/drhelius/Gearcoleco/assets/123488084/c6f830c0-13ee-4c9a-9ef9-079b70b3f5e3

**Comment by drhelius** [comment]
Found the issue.
In which platform are you running RA in this video? 
I see that Gearcoleco and Gearsystem are crashing on Android right now.
