### ISSUE TITLE
VDP Viewer: jump to memory location on tile click

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#53]
If you feel it is a good feature to implement and if you find the time.

While viewing the pattern table, sprite or name table inside the VDP viewer.

That if you double click on a tile within the grid that it will jump to where it is stored in the VRAM.

**Comment by drhelius** [comment]
Yes, this is easy to add. Thanks.

**Comment by KPreston2900050** [comment]
I just picked up the latest build.
You are a better man than I am.....

AMAZING!!!

**Comment by KPreston2900050** [comment]
Quick edit after more testing.

Clicking on a pattern in the Name Table Tab goes to the same address as the Pattern Table.

So if my Pattern Table starts at $0000 and my Name Table starts at $1800 and I click on an 8x8 square in the Name Table tab it should bounce to the data starting at $1800

Sprites act accordingly Starting at $3800

This opens up the second can of worms the color table for patterns and the attributes for sprites.
