### ISSUE TITLE
Red button won't register when using gamepad

### ISSUE THREAD

**Issue by goodstuff626** [drhelius/Gearcoleco#55]
I use ps3 wired controller to play games. When I start Congo Bongo, or Donkey Kong, the opening screen I need to press either number 1-8, but when I press 1 on my keyboard it does not select anything. I don't want to press a number from my joystick, as I don't know what buttons go to what numbers. In Colem emulator, I can use joystick, and press keyboard keys. Why disable keyboard when using a joystick in Gearcoleco? Or am I doing something wrong?

**Comment by drhelius** [comment]
Are you using desktop version or Retro Arch? You should use both at the same time. I'll check it out.

**Comment by goodstuff626** [comment]
> Are you using desktop version or Retro Arch? You should use both at the same time. I'll check it out.

I am using desktop version. Windows 10 64bit.

**Comment by goodstuff626** [comment]
Ok, I realized you have to use the number pad on the right side of the keyboard, not the numbers above the letters. So that is good. But now I realized there is another problem. Mapping buttons to my joystick (ps3 controller with xinput) only "yellow left" button works correctly. When I map "red right" to a button, it won't register when playing a game. But hitting "S" on my keyboard will register when playing a game. Is this a bug with the emulator?

**Comment by drhelius** [comment]
It's not possible to un-map buttons. I just created #57 to add this feature.

GUID is the GUIDE button in some gamepads.  I don't know why the name gets cropped. https://wiki.libsdl.org/SDL2/SDL_GameControllerButton

**Comment by drhelius** [comment]
Thanks for reporting about the "right" button. It was a typo in the code. Fixed now.
