### ISSUE TITLE
Sega Turbo stuck on skill select screen

### ISSUE THREAD

**Issue by r-moeritz** [drhelius/Gearcoleco#58]
Hi, thanks for a fantastic emulator! All games I've tried so far have worked well with the exception of Sega's Turbo, which gets stuck on the skill select screen. I tried the debugger, but I don't know anything about the ColecoVision's architecture or Z80 Assembly, so wasn't able to figure out where it was getting stuck. The md5sum of my copy of Turbo is `f042ba432716b58d2f5858abcce81b9f`, in case that helps. I am using the BIOS with md5sum `2c66f5911e5b42b8ebe113403548eee7`, as you recommended in the README.

![image](https://github.com/drhelius/Gearcoleco/assets/426109/db9f12b0-b174-4108-b91a-209c0871d0c2)

**Comment by drhelius** [comment]
Thanks for reporting!
I'll check it out.

**Comment by drhelius** [comment]
Turbo requires the Steering Wheel. You can enable it in the "Input -> Spinners" menu.

When the Steering Wheel is in use only action buttons in the first controller (red, yellow) work. All other buttons are used with the second player controller.

So, to start the game you must press a numeric key in the second controller. The throttle is the yellow button in the first controller.

**Comment by r-moeritz** [comment]
Oh, I see! Thanks for clearing that up. It's going to take some getting used to the controls.
