### ISSUE TITLE
Quick edit after more testing pattern mem jump

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#59]
Quick edit after more testing.

Clicking on an 8x8 square in the Name Table Tab goes to the same address as the Pattern Table Tab

So if my Pattern Table starts at $0000 and my Name Table starts at $1800 and I click on an 8x8 square in the Name Table tab it should bounce to the data starting at $1800

Sprites act accordingly Starting at $3800

This opens up the second can of worms the color table for patterns and the attributes for sprites.
Those are two tables that would have to have tabs created.  At least the color table.

_Originally posted by @KPreston2900050 in https://github.com/drhelius/Gearcoleco/issues/53#issuecomment-2172364341_

**Comment by drhelius** [comment]
Yes you are right. I thought it has more sense to point to tile memory on click in the name table tab also, but probably not.

For colors, I'm going to create a palette viewer like in Gearsystem, that will work better:

![image](https://github.com/drhelius/Gearcoleco/assets/863613/082295ff-7936-40ff-9afe-eb1713bc7292)

**Comment by drhelius** [comment]
I totally forgot this is TMS9918 so no possibility to change palette color.

**Comment by drhelius** [comment]
I don't know how to represent the color table in its own tab. It's implicitly implemented in the name table add.

I can add the address to the color table for a specific tile in the right section of the name table tab.

**Comment by drhelius** [comment]
> I thought about the color table as well and it would be redundant info. A tab much like the pattern tab but when you click on the 8x8 tile it jumps to where it is on the color table that usually starts at $2000.

Please, if you have the time, review the latest commit. It now shows the color addr in the name table tab on the right. This way you can jump manually using the goto box in the memory editor. 

Each tile on the name table tab will jump to the correct tile in the name table address.

I don't want to duplicate a tab just to change the behavior of the mouse click.

If it's working right I'll leave it as it is.

**Comment by KPreston2900050** [comment]
The Color address is a great compromise.
I wasn't a fan of another tab sitting there wasting space.

**Comment by drhelius** [comment]
Done.
But 16 is still the default number of columns. Maybe in the future I'll save the state of the memory editor, but for now it will reset on exit.

**Comment by KPreston2900050** [comment]
![Screenshot (32)](https://github.com/drhelius/Gearcoleco/assets/31710909/6226d51b-c495-46f2-9927-52dca0fddaef)
Blown away

**Comment by KPreston2900050** [comment]
Update
I j was going through the features and found that the Sprite address jumping no longer works
I tested it with Gearcoleco-1.1.0-44-ga9548a8-windows-x64 and it works fine with that version.

The latest Gearcoleco-1.1.0-47-g4818bd0-windows-x64 does not work anymore.

**Comment by drhelius** [comment]
Sorry I messed up trying to avoid activity when window is out of focus.

**Comment by KPreston2900050** [comment]
Works like a charm.

I am telling you strait up. Aside from MAME/MESS this is the top version with the most features out there.  MAME is an all around, over bloated emulator where this hits the mark.  I just want to know why no one else could do it.

C++, Visual studio, Open source.
What is not to love.

**Comment by KPreston2900050** [comment]
Is there any way to dock all the smaller windows in a way that it becomes one one unit which will stay the way you left it.
I mean also, where you left the program where you closed it.  It seems to always boot up in the middle of the screen.

My thinking is a radio switch that when clicked everything becomes one window which scales when you pull on a corner.

**Comment by drhelius** [comment]
Not yet. There is a "docking" branch in development in [Dear ImGui](https://github.com/ocornut/imgui) with docking and multi viewport support. I may support that in the future but I think it requires a lot of changes.

For now, Dear ImGui saves the window position on exit but as soon as you resize the window to a smaller size it tries to pack all its windows in the available space on boot up. I'm saving the size of the main window though, but again, if the main window gets resized to a smaller size, ImGui will pack its windows in this smaller space.

It's not an easy fix, it depends on the gui library but I probably try to improve it in the future when this "docking" branch is merged.

A workaround for me is keeping always the same size for the main window.

**Comment by drhelius** [comment]
I ended up adding the docking support. But kept it optional: You have to press SHIFT when moving windows around.
I also added multi-viewport as an option. It only works on Windows an Mac. But this way you can position debugger windows in multiple monitors. It requires a restart each time you enable/disable it though.

**Comment by KPreston2900050** [comment]
I would say truthfully, from my observations, your Colecovision emulator has become the number one version among my peers for the Colecovision.  And in short time.

I think the others became complacent and when you brought up inconsistencies or issues you would be shut down.
I had that same issue with the guy who wrote ColEm.  Now, he does not even bother with it outside of his selling a version in the android store.

All of my emulators for the other systems in this series Gameboy, MSX...  I have already converted over to your version.

Yours is just super versatile and user friendly.

I exchanged the Coleco BIOS with the Pencil II and it actually worked up until a point.
I loaded a game but it crashed when it looked for expansion memory at $2000 or some deal.

So, that may be an idea for new emulator as an exercise.  I say exercise because you can only find like 4 games for the entire system.  Also, it is more of a computer system with expansion than a console.

I have been able to get a portion of ADAM working in experimentation.  Being as the SGM ram will allow you to load anything, I was able to load in an ADAM Super Game and run it up till it using the 6801.  But I am getting there.
I just do not know how to use visual studio very well.

The dock works great after the learning curve.

**Comment by drhelius** [comment]
Thanks for your kind words. I truly appreciate it.
