### ISSUE TITLE
Crashes if no audio device found

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#63]
I learned this by accident and a few computer resets.

The other day I booted up Gear Coleco and it crashed big time.  I could not get the thing to work.

Later, after an hour of diagnosing I gave up then tried to play some music just to notice that both my sound bar and headset were turned off.

After turning them on, Gear Coleco worked.
I did some fooling around and it does not matter if Gear Coleco Audio is disabled or not.  It will crash if you have no sound output.

I don't know if you care.  Hey, turn your speakers on knucklehead.  Or, you want perfection and fix all the bugs that show up from time to time.

Of course it is something in the initialization of devices, maybe SDL2 does not initialize without a sound device, I have no clue but I wanted to share this finding with you in any case.

cheers

**Comment by drhelius** [comment]
Yes, I can definitely handle when no audio device is working so it doesn't crash.

Thanks for reporting.
