### ISSUE TITLE
Larger multiplier for output window in debug mode

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#66]
With all the windows in debug mode would it be possible to use a larger multiplier or lower right hand corner to make the output window larger when undocked.

The largest you can make it is x3 which is quite small on my 5k monitor.

I thought I would run it by you because it never hurts to ask.

I could not find a request tab so I ended up writing this in the issues area.

TIA

**Comment by drhelius** [comment]
It's perfectly fine to ask for requests here, thanks!

**Comment by drhelius** [comment]
Changed the scaling settings a bit. Now there is a manual integer scale setting from 1 to 10. Hope that helps.

**Comment by KPreston2900050** [comment]
OMG I LOVE YOU MAN!

It's the best ever.
