### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by siriokds** [drhelius/Gearcoleco#67]
Hi, digging in your code I found this (Processor.cpp - row 207), I don't know if "|" instead "||" is an error but I want to signal it to you :)

void Processor::ExecuteOPCode()
{
    u8 opcode = FetchOPCode();

    switch (opcode)
    {
        case 0xDD:
        case 0xFD:
        {
            int more_prefixes = false;
            while ((opcode == 0xDD) | (opcode == 0xFD))            <<<<<<<<<<<<<<<<
            {

**Comment by drhelius** [comment]
Nice catch! Yes is a typo, but in reality it works the same because false converts to zero and true converts to one as integers.

I'll fix it to avoid confusion anyway.
