### ISSUE TITLE
Ram/VRAM Save (export) / Load (import)

### ISSUE THREAD

**Issue by siriokds** [drhelius/Gearcoleco#69]
Is it possible to Save (export) / Load (import) part of ram or VRAM? 

It could be useful for debug purposes.

I'm trying to study dear imgui to figure out if a context menu is doable to add commands (examples to a memory selected range).

**Comment by drhelius** [comment]
Yes it's possible.
Check my most recent emulator https://github.com/drhelius/Geargrafx

I will probably port of that features to Gearcoleco.

**Comment by drhelius** [comment]
Done!
