### ISSUE TITLE
Possible new issue (Controller 2)

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#70]
For some reason I can not define Controller 2.
When I click on the area it keeps inputting the letter K then no ability to change it at all.
Now 0,1 and 2 are all K for controller 2

I do not want to test redefining controller 1 to see if it is both because if I mess with it I will not have the ability to change it back.

**Comment by drhelius** [comment]
I updated Imgui so it could be a regression, I'll check it out.
Are you using 1.3.0 or latest commit?
Thanks for reporting.

**Comment by drhelius** [comment]
Yes, it was the Imgui update and all my emus are affected. Looks like an easy fix.

**Comment by drhelius** [comment]
I think it's fixed. I added the possibility to un-map keys and buttons too.
