### ISSUE TITLE
Redefining Keys

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#71]
I thought I posted this last night and now I don't see it.

It started by trying to redefine controller 2 keys and getting nothing but a "K" and locking up the ability to redefine.

I deleted the settings and started from scratch.
Now when you try to redefine a key in either controller it shows up as "AC REFRESH" then prevents you from changing the key after that.

Never Mind, found that you fixed the issue in today's build.

thanks

**Comment by drhelius** [comment]
Please try the latest build when you can and let me know if it works.

I solved a problem with the keyboard not working when redefining, but I'm not sure if you are referring to game pads or keyboard.

**Comment by KPreston2900050** [comment]
Your latest build works fine as far as the keyboard keys.
I don't think I ever used the game pads.

One day I would like to read and understand your code so I can make an ADAM Branch.
My issue is how to add a 6801 to work along side the Z80.

I know assembly, C++ not so much
