### ISSUE TITLE
Bilinear filtering causes undesired texture wrapping

### ISSUE THREAD

**Issue by npiegdon** [drhelius/Gearcoleco#8]
(You've done great work!  This debugger is amazing.)

Just a small rendering artifact: when bilinear filtering is enabled and you've got the screen large enough that it's being scaled up, the bottom/top row of pixels can bleed onto each other.

Fixing it should just take changing the wrap mode for the output screen texture from "repeat" to "clamp-to-edge".

**Comment by drhelius** [comment]
Thanks for reporting and pointing to the solution!
